services:
  db:
    image: postgres
    container_name: db
    volumes:
      - postgres:/var/lib/postgresql/data 
    ports:
      - "5432:5432"    
  web:
    build: .
    container_name: web
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/meter
    ports:
      - "3000:3000"
    depends_on:
      - db  
